name: Java CI with Gradle

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: MacOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.10
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.10'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: EventRegistration-Backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: EventRegistration-Backend
